default:
  plugins:
    - link

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table
    
# https://www.tinymce.com/docs/configure/   Options disponibles